trigger:
- main

pool:
  name: 'LinuxAgents'

steps:
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'TerraformARM'
    backendAzureRmOverrideSubscriptionID: '$(SubID)'
    backendAzureRmResourceGroupName: '$(SARG)'
    backendAzureRmStorageAccountName: '$(SAName)'
    backendAzureRmContainerName: '$(CName)'
    backendAzureRmKey: '$(SAKey)'
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'TerraformARM'
    environmentAzureRmOverrideSubscriptionID: '$(SubID)'
- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'TerraformARM'
    environmentAzureRmOverrideSubscriptionID: '$(SubID)'